-- 코드를 입력하세요
SELECT t1.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES, ADDRESS, ROUND(AVG(t2.REVIEW_SCORE),2) AS SCORE 
FROM REST_INFO t1 
RIGHT JOIN REST_REVIEW t2 ON t1.REST_ID = t2.REST_ID
WHERE SUBSTRING_INDEX(TEL,"-",1) = 02 OR ADDRESS LIKE "서울%"
GROUP BY t1.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;