-- 코드를 입력하세요
SELECT TIME_FORMAT(DATE_FORMAT(DATETIME,"%T"),"%H") AS HOUR, COUNT(*)
FROM ANIMAL_OUTS
WHERE TIME_FORMAT(DATE_FORMAT(DATETIME,"%T"),"%H") BETWEEN "09" AND "19"
GROUP BY HOUR
ORDER BY HOUR ASC;